### ISSUE TITLE
KtLintConfigurator fails to find tasks

### ISSUE THREAD

**Issue by tasomaniac** [novoda/gradle-static-analysis-plugin#129]
Just tried to integrate it into our project. Unfortunately SAP is failing to resolve the `ktlint` tasks even thought tasks are actually present. I think it is a timing issue. 

```
Caused by: org.gradle.api.UnknownTaskException: Task with name 'ktlintWayfairTangoDisabledDebugAndroidTestCheck' not found in project ':app'.
        at org.gradle.api.internal.tasks.DefaultTaskCollection.createNotFoundException(DefaultTaskCollection.java:88)
        at org.gradle.api.internal.tasks.DefaultTaskCollection.createNotFoundException(DefaultTaskCollection.java:39)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection.getByName(DefaultNamedDomainObjectCollection.java:320)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection.getAt(DefaultNamedDomainObjectCollection.java:339)
        at org.gradle.api.internal.tasks.DefaultTaskCollection.getAt(DefaultTaskCollection.java:39)
        at com.novoda.staticanalysis.internal.ktlint.KtlintConfigurator$_createCollectViolationsTask_closure6.doCall(KtlintConfigurator.groovy:94)
```

**Comment by rock3r** [comment]
Is the KtLint plugin using `afterEvaluate`? Because that would explain the issue.

I have [set it up on Squanchy](https://github.com/squanchy-dev/squanchy-android/pull/585) tho and it works fine.

**Comment by tasomaniac** [comment]
It was also working fine for me for couple of simpler personal projects. I didn't investigate further but I'm suspecting a timing issue resulting because of the size of Wayfair app.

I've linked an issue I opened in KtLint. It is probably because of afterEvaluate

**Comment by mr-archano** [comment]
Dammit. Nested `afterEvaluate` are PITA. I wonder if there's anything else we can do to prevent the issue altogether - a callback similar to `plugins.withId` maybe, like `tasks.withType()`? Not sure...

**Comment by tasomaniac** [comment]
I am solving for now in our project by adding another afterEvaluate lol 😀

**Comment by tasomaniac** [comment]
Actually this is supposed to be fixed with Ktlint plugin version 6.x and later. But #140 prevents me to verify that.
