### ISSUE TITLE
Detekt: Exception when output is null

### ISSUE THREAD

**Issue by tasomaniac** [novoda/gradle-static-analysis-plugin#70]
It seems that the output is not mandatory in detekt. When you don't have any output defined, it simply skips writing to files and only does console output. 

But when it is integrated through our plugin, we just throw `IllegalArgumentException` with a cryptic message. Instead, maybe we should validate it and require `output` to be define. 

<details>
Caused by: java.lang.IllegalArgumentException: path may not be null or empty string. path='null'
        at org.gradle.api.internal.file.AbstractBaseDirFileResolver.doResolve(AbstractBaseDirFileResolver.java:65)
        at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:85)
        at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:67)
        at org.gradle.api.internal.file.DefaultFileOperations.file(DefaultFileOperations.java:89)
        at org.gradle.api.internal.project.DefaultProject.file(DefaultProject.java:840)
        at org.gradle.api.Project$file$3.call(Unknown Source)
        at com.novoda.staticanalysis.internal.detekt.DetektConfigurator.createCollectViolationsTask(DetektConfigurator.groovy:67)
        at com.novoda.staticanalysis.internal.detekt.DetektConfigurator.configureToolTask(DetektConfigurator.groovy:61)
        at com.novoda.staticanalysis.internal.detekt.DetektConfigurator$_execute_closure1.doCall(DetektConfigurator.groovy:50)
</details>

**Comment by mr-archano** [comment]
Good point @tasomaniac. To me this looks like a bug we need to fix.

**Comment by tasomaniac** [comment]
Yep. we may have such problems time to time with all the tools. 

We have some expectations from the user how to configure the tools. Having an `output` for detekt is only 1 example. And we should have clear error messages around those expectations.

**Comment by mr-archano** [comment]
@tasomaniac is this issue supposed to track also the improvements for the other tools?

**Comment by tasomaniac** [comment]
Fixed by #90

**Comment by tasomaniac** [comment]
@mr-archano I just mentioned that but I cannot recall at the moment similar problems with other tools.
